# Generated by Django 5.1.1 on 2024-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_rename_original_name_uploadedfile_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="status",
            field=models.CharField(
                choices=[("uploaded", "Uploaded"), ("compressed", "Compressed")],
                default="uploaded",
                max_length=50,
            ),
        ),
    ]
